export const MESSAGES_PAGE = "MESSAGES";
export const GOALS_DETAIL_PAGE = "GOALS_DETAIL";

export const CONVERSATIONS_TYPE_USER = "USER";
export const CONVERSATIONS_TYPE_AI = "AI";

export const ACTION_SEND_EMAIL = "SEND_EMAIL";
export const ACTION_SEND_SMS = "SEND_SMS";
export const AUTH_ACTION_AT_THE_BEGINNING = "AT_THE_BEGINNING";
export const AUTH_ACTION_AFTER_MESSAGES = "AFTER_MESSAGES";
export const AUTH_METHODS = [ACTION_SEND_EMAIL, ACTION_SEND_SMS];
export const AUTH_ACTIONS = [AUTH_ACTION_AT_THE_BEGINNING, AUTH_ACTION_AFTER_MESSAGES];

export const TIME_AUTO_HIDE_DURATION = 6000;

export const POSITION_TOP_CENTER_FLOATING = "top-center-floating";
export const POSITION_BOTTOM_CENTER_FLOATING = "bottom-center-floating";
export const POSITION_BOTTOM_RIGHT_FLOATING = "bottom-right-floating";
export const POSITION_PLACED_FLOATING = "placed-floating";
export const POSITION_PLACED_INLINE = "placed-inline";

export const POSITIONS = [
  POSITION_TOP_CENTER_FLOATING,
  POSITION_BOTTOM_CENTER_FLOATING,
  POSITION_BOTTOM_RIGHT_FLOATING,
  POSITION_PLACED_FLOATING,
  POSITION_PLACED_INLINE,
];

export const LANGUAGE_EN = "en";
export const LANGUAGE_ES = "es";
export const LANGUAGE_PT = "pt";
export const LANGUAGE_ZH = "zh";
export const LANGUAGE_ZH_HANS = "zh-hans";
export const LANGUAGE_ZH_HANT = "zh-hant";
export const LANGUAGE_ZH_YUE = "zh-yue";

export const LANGUAGES = [
  LANGUAGE_EN,
  LANGUAGE_ES,
  LANGUAGE_PT,
  LANGUAGE_ZH,
  LANGUAGE_ZH_HANS,
  LANGUAGE_ZH_HANT,
  LANGUAGE_ZH_YUE,
];

export const GOAL = "GOAL";
export const THREAD = "THREAD";
export const SPACE = "SPACE";

export const CHAT_STEP = "CHAT";
export const GOALS_STEP = "GOALS";
export const THREAD_STEP = "THREAD";

export const MODAL_STEPS = [CHAT_STEP, GOALS_STEP];

export const CHAT_VIEW = "CHAT_VIEW";
export const SEARCH_VIEW = "SEARCH_VIEW";
export const BROWSE_VIEW = "BROWSE_VIEW";
export const AGENT_VIEW = "AGENT_VIEW";
export const MODAL_VIEWS = [CHAT_VIEW, SEARCH_VIEW, BROWSE_VIEW];

export const GOAL_COMPLETED = "COMPLETED";
export const GOAL_ACTIVE = "ACTIVE";
export const GOAL_CANCELLED = "CANCELLED";
export const GOAL_NOT_STARTED = "NOT_STARTED";

export const START_MODE_QUESTIONS = "QUESTIONS";
export const START_MODE_GOALS = "GOALS";

export const GOAL_ACTIONS_AVAILABLE_STATUS_ACTIVE = "ACTIVE";
export const GOAL_ACTIONS_AVAILABLE_STATUS_DISABLED = "DISABLED";

export const GOAL_ACTIONS_TYPE_CALENDLY = "CALENDLY";
export const GOAL_ACTIONS_TYPE_HUBSPOT = "HUBSPOT";
export const GOAL_ACTIONS_TYPE_CIRRUS_INSIGHTS = "CIRRUS_INSIGHTS";
export const GOAL_ACTIONS_TYPE_SHOW_WEBPAGE = "SHOW_WEBPAGE";
export const GOAL_ACTIONS_TYPE_WEB_LINK = "WEB_LINK";

export const GOAL_ACTIONS_TYPE_WEB_ACTIONS = [
  GOAL_ACTIONS_TYPE_SHOW_WEBPAGE,
  GOAL_ACTIONS_TYPE_WEB_LINK,
];

export const GOAL_ACTIONS_TYPE_WEB_IFRAME = [
  GOAL_ACTIONS_TYPE_SHOW_WEBPAGE,
  GOAL_ACTIONS_TYPE_CALENDLY,
];

export const GOAL_ACTIONS_TYPE_SEO_VIEW = [GOAL_ACTIONS_TYPE_WEB_LINK];

export const GOAL_ACTIONS_TYPE_MEETING_ACTIONS = [
  GOAL_ACTIONS_TYPE_CALENDLY,
  GOAL_ACTIONS_TYPE_HUBSPOT,
  GOAL_ACTIONS_TYPE_CIRRUS_INSIGHTS,
];

// Methods for actions
export const GOAL_ACTIONS_METHOD_SHOW = "SHOW";
export const GOAL_ACTIONS_METHOD_WEBHOOK = "WEBHOOK";
export const GOAL_ACTIONS_METHOD_API_CALL = "API_CALL";

export const GOAL_ACTIONS_METHODS = [
  GOAL_ACTIONS_METHOD_SHOW,
  GOAL_ACTIONS_METHOD_WEBHOOK,
  GOAL_ACTIONS_METHOD_API_CALL,
];

export const TYPE_OF_DOCUMENTS = ["pdf", "csv", "blob"];

export const GOAL_ACTIONS_TYPE_TITLE_ACTIONS = {
  [GOAL_ACTIONS_TYPE_SHOW_WEBPAGE]: "Check out our website",
  [GOAL_ACTIONS_TYPE_WEB_LINK]: "Check out our website",
  [GOAL_ACTIONS_TYPE_CALENDLY]: "Schedule a meeting",
  [GOAL_ACTIONS_TYPE_HUBSPOT]: "Schedule a meeting",
  [GOAL_ACTIONS_TYPE_CIRRUS_INSIGHTS]: "Schedule a meeting",
};

export const PAGE_NUMBER_DOCUMENT_DOWNLOAD_URL =
  "https://sharelyai-download-document/";

export const SPACE_SOURCE_TYPE_WEB_CONTROL = "WEB_CONTROL";

export const THUMB_UP = "THUMB_UP";
export const THUMB_DOWN = "THUMB_DOWN";
export const THUMB_SIGNALS = [THUMB_UP, THUMB_DOWN];

export const AVATAR_MODE_EXPANDED = "expanded";
export const AVATAR_MODE_COMPACT = "circle";
export const AVATAR_MODES = [AVATAR_MODE_EXPANDED, AVATAR_MODE_COMPACT];

export const SPACE_STATUS_PRIVATE = "PRIVATE";
export const SPACE_STATUS_PUBLIC = "PUBLIC";
export const SPACE_STATUS = [SPACE_STATUS_PRIVATE, SPACE_STATUS_PUBLIC];

export const USER_STATUS_PENDING = "PENDING";

export const CUSTOM_EVENTS = {
  TOGGLE_SAVE_CONVERSATION: "TOGGLE_SAVE_CONVERSATION",
  TOGGLE_SAVE_CONVERSATION_VIEW: "TOGGLE_SAVE_CONVERSATION_VIEW",
  OPEN_PDF_PREVIEW: "OPEN_PDF_PREVIEW",
  CLOSE_PDF_PREVIEW: "CLOSE_PDF_PREVIEW",
};

export const LOCAL_STORAGE_KEYS = {
  PUBLIC_SPACE_TOKEN: "public-space-token",
};

export const COOKIES_KEYS = {
  TEMPORAL: "temporal-token",
  MY_ACCESS: "my-access-token",
  MY_ACCESS_SPACE: "my-access-token-space",
  API_KEY_ACCESS: "apikey-access-token",
  AUTH_PROVIDER_TOKEN: "auth-provider-token",
  AUTH_PROVIDER_USER_ID: "auth-provider-user-id",
};

export const REGISTRATION_BY_EMAIL = "EMAIL";
export const REGISTRATION_BY_OTP = "OTP";
export const REGISTRATION_BY = [REGISTRATION_BY_EMAIL, REGISTRATION_BY_OTP];

export const DISPLAY_MODE = {
  MODE: {
    PUBLIC: "PUBLIC",
    PRIVATE: "PRIVATE",
  },
  VIEWS: {
    CHAT: "CHAT",
    SEARCH: "SEARCH",
  },
};

export const SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM_SPACE = "SPACE";
export const SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM_GOAL = "GOAL";
export const SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM = [
  SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM_SPACE,
  SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM_GOAL,
];

export const WORKFLOW_MESSAGE_FROM_TYPE_SPACE = "SPACE";
export const WORKFLOW_MESSAGE_FROM_TYPE_GOAL = "GOAL";
export const WORKFLOW_MESSAGE_FROM_TYPE = [
  WORKFLOW_MESSAGE_FROM_TYPE_SPACE,
  WORKFLOW_MESSAGE_FROM_TYPE_GOAL,
];

export const MIMETYPE_TEXT = "text/plain";
export const MIMETYPE_TEXT_CSV = "text/csv";
export const MIMETYPE_VIDEO_MP4 = "video/mp4";
export const MIMETYPE_IMAGE_PNG = "image/png";
export const MIMETYPE_IMAGE_GIF = "image/gif";
export const MIMETYPE_AUDIO_MP3 = "audio/mpeg";
export const MIMETYPE_IMAGE_JPEG = "image/jpeg";
export const MIMETYPE_IMAGE_WEBP = "image/webp";
export const MIMETYPE_APPLICATION_PDF = "application/pdf";
export const MIMETYPE_APPLICATION_ZIP = "application/zip";
export const MIMETYPE_APPLICATION_RAR = "application/x-rar-compressed";
export const MIMETYPE_APPLICATION_JSON = "application/json";
export const MIMETYPE_APPLICATION_MSWORD = "application/msword";
export const MIMETYPE_APPLICATION_VND_MS_EXCEL = "application/vnd.ms-excel";
export const MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET =
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
export const MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
export const MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION =
  "application/vnd.openxmlformats-officedocument.presentationml.presentation";
export const MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT =
  "application/vnd.google-apps.document";
export const MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET =
  "application/vnd.google-apps.spreadsheet";
export const MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION =
  "application/vnd.google-apps.presentation";
export const MIMETYPES = [
  MIMETYPE_TEXT,
  MIMETYPE_TEXT_CSV,
  MIMETYPE_VIDEO_MP4,
  MIMETYPE_IMAGE_PNG,
  MIMETYPE_IMAGE_GIF,
  MIMETYPE_AUDIO_MP3,
  MIMETYPE_IMAGE_JPEG,
  MIMETYPE_IMAGE_WEBP,
  MIMETYPE_APPLICATION_PDF,
  MIMETYPE_APPLICATION_ZIP,
  MIMETYPE_APPLICATION_RAR,
  MIMETYPE_APPLICATION_JSON,
  MIMETYPE_APPLICATION_MSWORD,
  MIMETYPE_APPLICATION_VND_MS_EXCEL,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION,
];

export const MIMETYPE_TO_EXTENSION = {
  [MIMETYPE_TEXT]: "txt",
  [MIMETYPE_TEXT_CSV]: "csv",
  [MIMETYPE_VIDEO_MP4]: "mp4",
  [MIMETYPE_IMAGE_PNG]: "png",
  [MIMETYPE_IMAGE_GIF]: "gif",
  [MIMETYPE_AUDIO_MP3]: "mp3",
  [MIMETYPE_IMAGE_JPEG]: "jpeg",
  [MIMETYPE_IMAGE_WEBP]: "webp",
  [MIMETYPE_APPLICATION_PDF]: "pdf",
  [MIMETYPE_APPLICATION_ZIP]: "zip",
  [MIMETYPE_APPLICATION_RAR]: "rar",
  [MIMETYPE_APPLICATION_JSON]: "json",
  [MIMETYPE_APPLICATION_MSWORD]: "doc",
  [MIMETYPE_APPLICATION_VND_MS_EXCEL]: "xls",
  [MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET]:
    "xlsx",
  [MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT]:
    "docx",
  [MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION]:
    "pptx",
  [MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT]: "docx",
  [MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET]: "xlsx",
  [MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION]: "pptx",
  LINK: "link",
};

export const SPACE_EVENTS = {
  SPACE_EVENT_SEARCH_TERM: "SEARCH_TERM",
  SPACE_EVENT_CLICKED_SEARCH_RESULT: "CLICKED_SEARCH_RESULT",
  SPACE_EVENT_CLICKED_CATEGORY_IN_BROWSE: "CLICKED_CATEGORY_IN_BROWSE",
  SPACE_EVENT_CLICKED_RESOURCE_IN_CATEGORY: "CLICKED_RESOURCE_IN_CATEGORY",
};

export const constants = {
  CUSTOM_EVENTS,
  CONVERSATIONS_TYPE_USER,
  CONVERSATIONS_TYPE_AI,
  ACTION_SEND_EMAIL,
  ACTION_SEND_SMS,
  AUTH_ACTION_AT_THE_BEGINNING,
  AUTH_ACTION_AFTER_MESSAGES,
  AUTH_METHODS,
  AUTH_ACTIONS,
  TIME_AUTO_HIDE_DURATION,
  POSITION_TOP_CENTER_FLOATING,
  POSITION_BOTTOM_CENTER_FLOATING,
  POSITION_BOTTOM_RIGHT_FLOATING,
  POSITION_PLACED_FLOATING,
  POSITION_PLACED_INLINE,
  POSITIONS,
  LANGUAGE_EN,
  LANGUAGE_ES,
  LANGUAGE_PT,
  LANGUAGE_ZH,
  LANGUAGE_ZH_HANS,
  LANGUAGE_ZH_HANT,
  LANGUAGE_ZH_YUE,
  LANGUAGES,
  CHAT_STEP,
  GOAL,
  THREAD,
  SPACE,
  GOALS_STEP,
  THREAD_STEP,
  MODAL_STEPS,
  CHAT_VIEW,
  SEARCH_VIEW,
  BROWSE_VIEW,
  AGENT_VIEW,
  MODAL_VIEWS,
  GOAL_COMPLETED,
  GOAL_ACTIVE,
  GOAL_CANCELLED,
  GOAL_NOT_STARTED,
  MESSAGES_PAGE,
  GOALS_DETAIL_PAGE,
  START_MODE_GOALS,
  START_MODE_QUESTIONS,
  GOAL_ACTIONS_AVAILABLE_STATUS_ACTIVE,
  GOAL_ACTIONS_AVAILABLE_STATUS_DISABLED,
  GOAL_ACTIONS_TYPE_CALENDLY,
  GOAL_ACTIONS_TYPE_HUBSPOT,
  GOAL_ACTIONS_TYPE_CIRRUS_INSIGHTS,
  GOAL_ACTIONS_TYPE_SHOW_WEBPAGE,
  GOAL_ACTIONS_TYPE_WEB_LINK,
  GOAL_ACTIONS_TYPE_WEB_ACTIONS,
  GOAL_ACTIONS_TYPE_WEB_IFRAME,
  GOAL_ACTIONS_TYPE_SEO_VIEW,
  GOAL_ACTIONS_TYPE_MEETING_ACTIONS,
  GOAL_ACTIONS_METHOD_SHOW,
  GOAL_ACTIONS_METHOD_WEBHOOK,
  GOAL_ACTIONS_METHOD_API_CALL,
  GOAL_ACTIONS_METHODS,
  GOAL_ACTIONS_TYPE_TITLE_ACTIONS,
  TYPE_OF_DOCUMENTS,
  PAGE_NUMBER_DOCUMENT_DOWNLOAD_URL,
  SPACE_SOURCE_TYPE_WEB_CONTROL,
  THUMB_UP,
  THUMB_DOWN,
  THUMB_SIGNALS,
  AVATAR_MODE_EXPANDED,
  AVATAR_MODE_COMPACT,
  AVATAR_MODES,
  LOCAL_STORAGE_KEYS,
  COOKIES_KEYS,
  SPACE_STATUS_PRIVATE,
  SPACE_STATUS_PUBLIC,
  SPACE_STATUS,
  USER_STATUS_PENDING,
  REGISTRATION_BY_EMAIL,
  REGISTRATION_BY_OTP,
  REGISTRATION_BY,
  DISPLAY_MODE,
  SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM_SPACE,
  SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM_GOAL,
  SPACE_CONVERSATION_RETRIVAL_DATA_DEBUG_CONTENT_FROM,
  WORKFLOW_MESSAGE_FROM_TYPE_SPACE,
  WORKFLOW_MESSAGE_FROM_TYPE_GOAL,
  WORKFLOW_MESSAGE_FROM_TYPE,
  MIMETYPE_APPLICATION_JSON,
  MIMETYPE_TEXT,
  MIMETYPE_TEXT_CSV,
  MIMETYPE_VIDEO_MP4,
  MIMETYPE_IMAGE_PNG,
  MIMETYPE_IMAGE_GIF,
  MIMETYPE_AUDIO_MP3,
  MIMETYPE_IMAGE_JPEG,
  MIMETYPE_IMAGE_WEBP,
  MIMETYPE_APPLICATION_PDF,
  MIMETYPE_APPLICATION_ZIP,
  MIMETYPE_APPLICATION_RAR,
  MIMETYPE_APPLICATION_MSWORD,
  MIMETYPE_APPLICATION_VND_MS_EXCEL,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT,
  MIMETYPE_APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_DOCUMENT,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_SPREADSHEET,
  MIMETYPE_APPLICATION_VND_GOOGLE_APPS_PRESENTATION,
  MIMETYPES,
  MIMETYPE_TO_EXTENSION,
  SPACE_EVENTS,
};
